version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ../../../docker/multistagebuild/Dockerfile
    ports:
      - "80:3333"
    environment:
      - ADDRESS=redis:6379
    depends_on:
      - redis
  redis:
    image: "redis:latest"
