version: '3'
services:
  api:
    build:
      context: .
      args:
        TARGETPLATFORM: amd64
    ports:
      - "8080:3333"
    environment:
      - ADDRESS=redis:6379
    depends_on:
      - redis
  redis:
    image: "redis:latest"
