version: '3'
services:
  frontend:
    depends_on:
      - api
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webroot:/usr/share/nginx/html:ro
  api:
    build:
      context: ../../golang/API/
    image: api_api
    environment:
      - ADDRESS=redis:6379
      - LOGLEVEL=debug
    depends_on:
      - redis
  redis:
    image: "redis:latest"
