version: '3'
services:
  frontend:
    depends_on:
      - api
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf.template:/tmp/nginx.conf.template:ro
      - ./webroot:/usr/share/nginx/html:ro
    environment:
     - API_FQDN=http://api:3333/
    command: /bin/bash -c "envsubst < /tmp/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  api:
    build:
      context: ../../golang/API/
    image: api_api
    environment:
      - ADDRESS=redis:6379
      - LOGLEVEL=debug
    depends_on:
      - redis
  redis:
    image: "redis:latest"
